/**
 * Hand-authored audio transcripts for the Graph REACTIVATION lesson
 * (subject 9, seq 8). Two-host Socratic format: Leo frames graph traversal as one
 * machine whose behavior is set by the frontier container, and drives execution
 * speed; Maya is a skeptic who learned BFS, DFS, Dijkstra, Union Find, and
 * topological sort years ago and drills into why each is correct and where the
 * fill order or visited-marking bites. Speed-reactivation, not first-teach. No
 * page-structure or meta-authoring language (kept out to pass transcript-quality).
 */

// Top-level overview: >= 2700 words, stand-alone, reactivates the whole pattern.
export const OVERVIEW_SCRIPT = `Leo: Graphs are the other strong-but-stale area in your history — the imported evidence shows tree-and-graph, union-find, and topological work among your most-practiced tags, all a couple of years old. So we are not teaching graph search from scratch. We are reactivating it: rebuilding the speed to pick the right traversal, mark visited correctly, and code it calmly, because in an interview the bottleneck is never "do I understand BFS," it is "can I recall the exact frontier container and the visited discipline fast enough to write it without second-guessing."

Maya: Good, because I do remember all of these, but they blur together when I am under pressure. I see a grid or a graph and I freeze on which one to reach for. So what is the actual reactivation drill — what do I rehearse until the choice is automatic?

Leo: One idea unlocks most of it: graph traversal is a single machine, and the container you pull the next node from decides its personality. Keep a frontier of discovered-but-not-yet-processed nodes. Pull from a queue and you get breadth-first search, which fans out in rings of equal distance, so it hands you shortest paths in an unweighted graph. Pull from a stack, or use the call stack through recursion, and you get depth-first search, which plunges down one path before backing up, so it is the tool for connectivity, cycle detection, and topological order. Pull from a priority queue keyed by distance and you get Dijkstra, which always expands the cheapest-so-far node, so it hands you shortest paths when edges have non-negative weights. Same loop — pop a node, look at its neighbors, record and push the new ones — three containers, three behaviors.

Maya: That is a clean unification. But why does the queue specifically give me shortest paths — what is the causal chain from "first in, first out" to "minimum number of edges"?

Leo: Trace it exactly. Breadth-first search starts with the source at distance zero in the queue. Because a queue is first-in-first-out, you process every node at distance d before you ever touch a node at distance d plus one — the ring at distance one was all enqueued before any ring-two node, so it all comes out first. When you first pop a node and look at an unvisited neighbor, the path that discovered it is one edge longer than the current node's path, and because you are processing in nondecreasing distance order, that is the fewest edges possible to reach it. So the very first time breadth-first search reaches a node is along a shortest path. That is the causal chain: first-in-first-out forces nondecreasing distance, nondecreasing distance means first-discovery equals shortest, so you record the distance at discovery and never update it again.

Maya: So does that mean the moment I mark a node visited matters — when exactly do I mark it, and what breaks if I do it at the wrong time?

Leo: This is the single most common reactivation bug, so let us be precise. Mark a node visited at the moment you enqueue it, not when you dequeue it. If you wait until you pop a node to mark it, the same node can be pushed onto the queue several times by several neighbors before it is ever processed, and now your queue balloons and, worse, you can process it more than once and corrupt the distance. Mark on enqueue and each node enters the frontier exactly once. The rule to reload is: discovered equals visited. The instant a node is discovered and pushed, it is off the market — no other edge may enqueue it again. That one discipline keeps breadth-first search linear and correct.

Maya: Let me push on the multi-source version, because that is where I always hesitate. What changes when the problem starts with many sources at once, like rot spreading from every rotten cell in a grid?

Leo: Almost nothing changes, and that is the beauty of it — which is exactly why it is worth reactivating as its own reflex. Instead of seeding the queue with one source at distance zero, you seed it with every source at distance zero, all enqueued before the loop starts. Then you run the identical layer-by-layer loop. Each sweep of the current frontier is one time step; every fresh cell adjacent to the frontier flips and joins the next frontier. Because all sources started together, the layer a cell is reached on is its distance to the nearest source, not to any particular one. So "minutes until every orange rots" is just the number of layers the breadth-first search runs, and "is any orange unreachable" is just "is any fresh cell still fresh when the queue empties." Multi-source breadth-first search turns a scary-sounding simultaneous-spread problem into the same queue loop with a fatter starting frontier.

Maya: Give me a concrete picture of that grid spread so it sticks, because I reason better from a specific example than from the abstract loop.

Leo: Take the small three-by-three grid of oranges where only the top-left cell starts rotten and the other eight are fresh. Think of the rot like a ripple spreading in a pond from that one corner. Before the loop you enqueue that single corner cell and set fresh to eight. Minute one processes just that corner: its two orthogonal neighbors — the cell to its right in the top row and the cell below it in the first column — flip to rotten, get enqueued, and fresh drops to six. Minute two processes those two: they rot their fresh neighbors, three more cells flip, fresh drops to three. Minute three finishes the far cells. Lay the minutes out as a small table and each cell is stamped with its distance to that corner: zero, then one, then two, then the bottom-right corner at distance four along the grid. The answer is the largest stamp, four minutes, and because fresh reached zero, nothing is stranded. Change the top-left to fresh and leave a rotten cell walled off by a zero-marked gap, and fresh never hits zero — that is the negative-one case, an orange the ripple can never touch.

Maya: Now the one I most want reloaded, because I always slow down on it: Union Find. It is not a traversal at all, so where does it fit, and how exactly does it answer connectivity so fast?

Leo: Right, Union Find is a different tool for a different question, and keeping it distinct is half the battle. Traversals answer "can I walk from here to there," and they re-explore each time. Union Find answers "are these two nodes in the same connected group," and it maintains that answer incrementally as edges arrive, which is perfect for streaming edges or for counting components. The structure is a forest: every node points to a parent, and following parents leads to a representative root for its group. Two nodes are connected exactly when they share a root. To merge two groups you find both roots and point one root at the other. To make it fast you add two optimizations: path compression, where during a find you flatten the chain so nodes point closer to the root, and union by rank or size, where you always attach the shorter tree under the taller. Together they make each operation almost constant — the famous inverse-Ackermann bound — so a whole sequence of unions and finds is effectively linear.

Maya: Can you go deeper on why those two optimizations together give near-constant time, rather than just one of them?

Leo: Yes, and the intuition is worth reloading even if the proof is heavy. Union by rank alone keeps the trees shallow: by always hanging the smaller tree under the larger, no tree's height grows unless you merge two trees of equal height, so height stays logarithmic in the group size — that already caps a find at order log n. Path compression alone, without union by rank, also amortizes well because each find pays to flatten the path it walked, so repeated finds on the same chain get cheap fast. The magic is that when you use both, the flattening from compression and the balance from rank reinforce each other, and the amortized cost per operation drops below any fixed constant you can name for realistic input sizes — it grows like the inverse Ackermann function, which is at most four or five for any number of nodes you will ever see. So the reactivation target is: never write Union Find with just a bare parent array; always add the halving line in find and the rank comparison in union, and it is effectively free.

Maya: Let me go to ordering now, because topological sort is the one whose two versions confuse me. What is Kahn's algorithm actually doing, and why does it double as a cycle detector?

Leo: Kahn's is breadth-first search wearing a different hat, and seeing that connection is the reactivation win. You want an order of the nodes such that every edge points forward — every prerequisite before the thing that needs it. Compute each node's in-degree, the number of edges pointing at it. Any node with in-degree zero has no unmet prerequisite, so it can go first; seed the queue with all of them. Then repeatedly pop a node, append it to the order, and for each neighbor decrement its in-degree, because you have just satisfied one of its prerequisites; whenever a neighbor's in-degree hits zero, it is now free, so enqueue it. You produce a valid ordering as you go. And here is the cycle-detection gift: if the graph has a cycle, the nodes in that cycle can never reach in-degree zero, because each one is waiting on another one in the same cycle, so they never enter the queue. So if the order you produced has fewer nodes than the graph, a cycle exists. That is why Course Schedule returns an empty order exactly when the prerequisites are impossible.

Maya: How does that compare to the depth-first version of topological sort — what changes between Kahn's and the recursive one?

Leo: They reach the same kind of answer by opposite motions, and knowing both lets you pick under pressure. The depth-first version runs a recursion from each unvisited node, fully exploring all descendants first, and pushes a node onto a result list only after its entire subtree is done — that is post-order. Reverse that post-order list and you have a topological sort, because a node finishes after everything it depends on. Cycle detection there needs a third color or an on-stack marker: if the recursion ever reaches a node that is currently on the active call stack, you have found a back edge, which means a cycle. So Kahn's detects cycles by leftover nodes with positive in-degree; the depth-first version detects them by a gray, on-stack node. For most interviews I reach for Kahn's first, because the in-degree bookkeeping is easier to get exactly right at speed than the three-color recursion, but I keep the depth-first version ready for when the interviewer wants it.

Maya: Before we leave the containers, walk me through Dijkstra on a tiny weighted example, because the priority queue is where I stall and I want the causal chain nailed down.

Leo: Picture four nodes in a line with a shortcut. Take the example where the source is node one, and the edges with their weights are: one to two costs one, two to three costs one, three to four costs one, and a direct one to four costs seven. Imagine the heap as a bag that always hands you the cheapest unfinalized node. You start with distance zero on node one and push it. Pop node one at cost zero; relax its edges, so node two gets a tentative distance of one and node four gets a tentative seven, and you push both. The heap now holds node two at one and node four at seven, so it hands you node two first, because it is cheaper. Pop node two at one; relax to node three at two, push it. Pop node three at two; relax to node four, and two plus one is three, which beats the tentative seven, so node four improves to three and you push that better entry. Pop node four at three and finalize it. The stale seven entry still sitting in the heap gets popped later, but its distance is worse than the finalized three, so you skip it — that stale-entry skip is the one line people forget. The shortest path to node four is three, not the single direct edge of seven, and Dijkstra found it because it always expands the cheapest frontier node first, so the first time a node is popped, its distance is already final.

Maya: So does that mean the whole thing collapses the instant a weight is negative — what is the causal chain there?

Leo: Exactly, and trace it. Dijkstra's entire correctness rests on one promise: when you pop a node, no cheaper path to it can still exist, because every edge is non-negative, so any path through a not-yet-finalized node can only cost more. A negative edge breaks that promise directly — a later path could dip below the distance you already finalized, because adding a negative edge can lower a total. The moment that can happen, "finalize on first pop" is a lie, and Dijkstra reports a wrong distance without any warning. That is the causal chain: non-negative edges guarantee that the cheapest-frontier node is truly done, one negative edge voids the guarantee, so you switch to Bellman-Ford, which relaxes all edges repeatedly and tolerates negatives.

Maya: Let me name the traps so I catch them under pressure. Where do reactivated graph solutions actually go wrong?

Leo: Four traps, and they are almost never about the concept. One: the visited discipline — marking on dequeue instead of enqueue in breadth-first search, or forgetting visited entirely in a graph with cycles, which loops forever. Two: the frontier container mismatch — reaching for a plain queue on a weighted graph where you actually need Dijkstra's priority queue, so you report a path with fewer edges but higher cost as if it were shortest. Three: Dijkstra on negative edges — the moment an edge can be negative, the "expand the cheapest and finalize it" invariant breaks, because a later, cheaper path could still arrive, and you need Bellman-Ford instead. Four: Union Find without the optimizations, or forgetting that it answers connectivity but not actual paths. None of these are "I forgot how graphs work." They are execution details, and execution speed and accuracy on those details is exactly what reactivation drills.

Maya: Let me say the whole thing back to make sure it is reloaded. Graph traversal is one loop whose container sets its behavior: a queue gives breadth-first search and shortest unweighted paths, a stack or recursion gives depth-first search for connectivity and ordering, a priority queue gives Dijkstra for non-negative weighted shortest paths. Mark visited on enqueue so each node enters once. Multi-source breadth-first search just seeds every source at distance zero and counts layers. Union Find is a separate tool that answers connectivity incrementally with path compression and union by rank in near-constant time. Topological sort is Kahn's in-degree breadth-first search, which returns fewer nodes exactly when a cycle exists, or reversed depth-first post-order. And the bugs are visited timing, container mismatch, negative edges under Dijkstra, and bare Union Find — not the ideas themselves.

Leo: That is a complete reload, and the two things to underline are the container-picks-the-behavior mental model and the mark-on-enqueue discipline. The container choice is what converts "this is a graph problem" into the right algorithm in seconds: shortest unweighted means queue, weighted non-negative means heap, ordering or connectivity means depth-first or Union Find. And mark-on-enqueue is the single reflex that keeps every traversal linear and correct. Reactivation is not relearning graphs; it is making those two reflexes fast enough that the graph part of an interview costs you thinking about the problem, not thinking about the machinery.

Maya: So the goal is not to understand graphs again. It is to make the container choice and the visited discipline so automatic that recognizing the shape and writing the traversal happen almost together.

Leo: That is exactly it, and it is worth saying plainly one last time. Pick the frontier container from the question — queue for shortest unweighted, heap for weighted, stack or recursion for ordering — mark every node visited the instant it is discovered, and keep Union Find in your other hand for pure connectivity. Four reflexes, drilled until they are one fluent motion, and the whole stale-but-learned graph pattern is back at full interview speed.`;

// Part 1 (Rotting Oranges / multi-source BFS, layers = time): >= 200 words.
export const PART1_SCRIPT = `Leo: Start with breadth-first search in its most vivid form: multi-source spread on a grid, the rotting-oranges problem. The state is a frontier queue of cells that just became rotten. The key move is seeding: before the loop, enqueue every already-rotten cell at time zero, and count how many fresh cells exist.

Maya: So how does the loop turn into minutes, exactly?

Leo: Each pass processes the entire current frontier as one time step. You pop every cell currently in the queue, look at its four neighbors, and any neighbor that is still fresh becomes rotten, is enqueued, and decrements the fresh count. Because all sources started together at time zero, the pass on which a cell rots is its distance to the nearest source. So the number of passes that actually spread rot is the answer in minutes.

Maya: And how do I know if it is impossible?

Leo: After the queue drains, check the fresh count. If any orange is still fresh, it was never adjacent to the spreading front, so it can never rot — return negative one. If everything rotted, return the number of layers minus the initial seeding layer.

Maya: Why mark rotten right when I enqueue?

Leo: Because if you wait, two rotten neighbors could both enqueue the same fresh cell, and you would process it twice and miscount time. Flip it to rotten the instant you enqueue it, and each cell enters the frontier exactly once — linear time over the grid.`;

// Part 2 (Union Find / Number of Provinces, path compression + union by rank): >= 200 words.
export const PART2_SCRIPT = `Leo: Now a tool that is not a traversal at all: Union Find, on the number-of-provinces problem. The question is pure connectivity — how many connected groups are in this friend matrix — and Union Find answers it incrementally instead of re-walking the graph.

Maya: What is the actual structure?

Leo: A parent array where each node points toward a representative root. Two nodes are in the same province exactly when they share a root. You start with every node as its own root, so the component count is n. Each time an edge unites two different roots, you attach one under the other and decrement the count. Whatever the count is at the end is the number of provinces.

Maya: And the two optimizations everyone forgets?

Leo: Path compression and union by rank. In find, as you walk up to the root, re-point nodes closer to it — the halving trick — so future finds are shorter. In union, attach the shorter tree under the taller so height barely grows. Together they make each operation almost constant, the inverse-Ackermann bound.

Maya: Why decrement only when the roots differ?

Leo: Because if two nodes already share a root, that edge is redundant — it joins nothing new, and in fact a redundant edge is exactly a cycle. You only merge, and only decrement the province count, when find returns two different roots.`;
